# Generated by Django 5.2.7 on 2025-10-08 20:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_group_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groceryexpense',
            name='cost',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
